In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("../data/raw/customer_shopping_behavior.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)
display(df.head())

Dataset loaded successfully!
Shape: (3900, 18)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [3]:
print("\nMISSING VALUES")
display(
    df.isnull().sum()
)

MISSING VALUES

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [4]:
print("\nMISSING VALUES")
display(
    df.isnull().sum()
      .sort_values(ascending=False)
      .to_frame("Missing Values")
)

MISSING VALUES

                        Missing Values
Review Rating                       37
Customer ID                          0
Age                                  0
Payment Method                       0
Previous Purchases                   0
Promo Code Used                      0
Discount Applied                     0
Shipping Type                        0
Subscription Status                  0
Season                               0
Color                                0
Size                                 0
Location                             0
Purchase Amount (USD)                0
Category                             0
Item Purchased                       0
Gender                               0
Frequency of Purchases               0

In [5]:
print("\nDUPLICATE ROWS")
print("Exact duplicate rows:", df.duplicated().sum())

print("\nSUMMARY STATISTICS")
display(df.describe(include="all").T)

DUPLICATE ROWS
Exact duplicate rows: 0

SUMMARY STATISTICS

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Customer ID,3900.0,NaN,NaN,NaN,1950.5,1125.977353,1.0,975.75,1950.5,2925.25,3900.0
Age,3900.0,NaN,NaN,NaN,44.068462,15.207589,18.0,31.0,44.0,57.0,70.0
Gender,3900,2,Male,2652,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Item Purchased,3900,25,Blouse,171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,3900,4,Clothing,1737,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Purchase Amount (USD),3900.0,NaN,NaN,NaN,59.764359,23.685392,20.0,39.0,60.0,81.0,100.0
Location,3900,50,Montana,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Size,3900,4,M,1755,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Color,3900,25,Olive,177,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Season,3900,4,Spring,999,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Review Rating,3863.0,NaN,NaN,NaN,3.750065,0.716983,2.5,3.1,3.8,4.4,5.0
Subscription Status,3900,2,No,2847,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shipping Type,3900,6,Free Shipping,675,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Discount Applied,3900,2,No,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Promo Code Used,3900,2,No,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Previous Purchases,3900.0,NaN,NaN,NaN,25.351538,14.447125,1.0,13.0,25.0,38.0,50.0
Payment Method,3900,6,PayPal,677,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Frequency of Purchases,3900,7,Every 3 Months,584,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
print("UNIQUE VALUES PER COLUMN")
display(df.nunique().sort_values().to_frame("Unique Values"))

print("\nCATEGORY DISTRIBUTIONS")

for col in ["Gender", "Category", "Subscription Status",
            "Discount Applied", "Payment Method"]:
    print(f"\n--- {col} ---")
    display(df[col].value_counts(dropna=False))

UNIQUE VALUES PER COLUMN

                        Unique Values
Promo Code Used                     2
Gender                              2
Discount Applied                    2
Subscription Status                 2
Category                            4
Size                                4
Season                              4
Shipping Type                       6
Payment Method                      6
Frequency of Purchases              7
Color                              25
Item Purchased                     25
Review Rating                      26
Location                           50
Previous Purchases                 50
Age                                53
Purchase Amount (USD)              81
Customer ID                      3900

CATEGORY DISTRIBUTIONS

--- Gender ---

Gender
Male      2652
Female    1248
Name: count, dtype: int64

--- Category ---

Category
Clothing       1737
Accessories    1240
Footwear        599
Outerwear       324
Name: count, dtype: int64

--- Subscription Status ---

Subscription Status
No     2847
Yes    1053
Name: count, dtype: int64

--- Discount Applied ---

Discount Applied
No     2223
Yes    1677
Name: count, dtype: int64

--- Payment Method ---

Payment Method
PayPal           677
Credit Card      671
Cash             670
Debit Card       636
Venmo            634
Bank Transfer    612
Name: count, dtype: int64